package com.simats.echohealth.utils

import android.content.Context
import android.graphics.pdf.PdfDocument
import android.graphics.Canvas
import android.graphics.Paint
import android.graphics.Typeface
import android.net.Uri
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object PdfGenerator {

    data class ReportData(
        val title: String,
        val riskLevel: String,
        val percentage: String,
        val mode: String,
        val infoText: String,
        val timestamp: String
    )

    fun generateReportPdf(context: Context, data: ReportData): Uri? {
        val doc = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 in points (approx)
        val page = doc.startPage(pageInfo)
        val canvas: Canvas = page.canvas

        val headerPaint = Paint().apply {
            isAntiAlias = true
            textSize = 18f
            typeface = Typeface.create(Typeface.DEFAULT_BOLD, Typeface.BOLD)
        }
        val subPaint = Paint().apply {
            isAntiAlias = true
            textSize = 12f
        }
        val boxPaint = Paint().apply {
            style = Paint.Style.STROKE
            strokeWidth = 2f
        }

        var y = 60f
        // Header
        canvas.drawText("EchoHealth", 40f, y, headerPaint)
        canvas.drawText(data.title, 200f, y, headerPaint)
        y += 30f
        canvas.drawText("Date: ${data.timestamp}", 40f, y, subPaint)
        y += 20f

        // Card box
        canvas.drawRect(30f, y, 565f, y + 140f, boxPaint)
        y += 30f
        canvas.drawText("Risk Level: ${data.riskLevel}", 50f, y, subPaint)
        y += 20f
        canvas.drawText("Prediction: ${data.percentage}", 50f, y, subPaint)
        y += 20f
        canvas.drawText("Mode: ${data.mode}", 50f, y, subPaint)
        y += 30f
        wrapText(canvas, "Details: ${data.infoText}", 50f, y, 500f, subPaint).also { y = it + 20f }

        // Footer
        canvas.drawText("Generated by EchoHealth – For awareness purposes only", 40f, 810f, subPaint)

        doc.finishPage(page)

        val outDir = File(context.cacheDir, "reports").apply { mkdirs() }
        val file = File(outDir, "risk_report_${System.currentTimeMillis()}.pdf")
        FileOutputStream(file).use { doc.writeTo(it) }
        doc.close()

        return FileProvider.getUriForFile(context, context.packageName + ".fileprovider", file)
    }

    private fun wrapText(canvas: Canvas, text: String, x: Float, startY: Float, maxWidth: Float, paint: Paint): Float {
        var y = startY
        val words = text.split(" ")
        var line = StringBuilder()
        for (word in words) {
            val test = if (line.isEmpty()) word else line.toString() + " " + word
            if (paint.measureText(test) > maxWidth) {
                canvas.drawText(line.toString(), x, y, paint)
                y += 18f
                line = StringBuilder(word)
            } else {
                line = StringBuilder(test)
            }
        }
        if (line.isNotEmpty()) canvas.drawText(line.toString(), x, y, paint)
        return y
    }
}


